ucb-rit/coldfront

- coldfront/core/allocation/admin.py
- coldfront/core/allocation/models.py
#21 
Add admin views for AllocationUserAttribute and AllocationUserAttributeUsage
> fix issue_21

- coldfront/core/project/templates/project/project_archive.html
- coldfront/core/project/templates/project/project_detail.html
- coldfront/core/project/views.py
#23 
A user can archive a project iff he/she has the superuser status.
> fix issue_23

- coldfront/core/portal/templates/portal/center_summary.html
- coldfront/core/user/templates/user/login.html
- coldfront/core/user/templates/user/passwords/password_change_form.html
- coldfront/core/user/templates/user/passwords/password_reset_complete.html
- coldfront/core/user/templates/user/passwords/password_reset_confirm.html
- coldfront/core/user/templates/user/passwords/password_reset_done.html
- coldfront/core/user/templates/user/passwords/password_reset_form.html
- coldfront/core/user/templates/user/registration.html
- coldfront/core/user/templates/user/user_profile.html
- coldfront/templates/common/base.html
- requirements.txt
Changes
- Update `requirements.txt` to use Django 3-compatible modules.
- Replace `load staticfiles` with `load static`.
> Upgrade to Django 3

- coldfront/core/allocation/templates/allocation/allocation_detail.html
- coldfront/core/allocation/views.py
- coldfront/core/project/templates/project/project_detail.html
- coldfront/core/project/views.py
> Move cluster account request to project view; remove add/remove user access

- coldfront/core/user/forms.py
- coldfront/core/user/templates/user/user_profile.html
- coldfront/core/user/templates/user/user_profile_update.html
- coldfront/core/user/urls.py
- coldfront/core/user/views.py
#89 
added:
- view for updating profile, through the user profile page
technical discussion:
- add additional value checks before updating fields
> enable users to edit their name

- coldfront/core/user/templates/user/user_profile.html
> update edit-name button placement in user-profile

- coldfront/core/user/templates/user/user_profile_update.html
> replace reset with cancel button in edit-name form

- coldfront/core/portal/templates/portal/authorized_home.html
> update cluster username highlighting on home page

- coldfront/core/portal/templates/portal/authorized_home.html
> add table headers to home page project lists

- coldfront/core/user/forms.py
#111 
add:
- basic help text to registration form
discuss:
- the style choices
> add basic help text to registration form

- coldfront/core/user/templates/user/user_profile.html
- coldfront/core/user/views.py
#135
- users can only edit their own names
- admins can edit any user's names
> users can only edit their own names

- coldfront/core/user/forms.py
- coldfront/core/user/templates/user/registration_form.html
- coldfront/core/user/urls.py
- coldfront/core/user/views.py
- coldfront/static/core/user/css/registration.css
- coldfront/static/core/user/js/registration.js
Fixes #116
**Changes**
- Added a view that returns whether the given email address already exists in the system.
- Added JavaScript code to make a request to the view when the user stops typing, and return the response.
> Give immediate feedback for email conflicts during registration

- coldfront/core/user/templates/user/registration_form.html
- coldfront/core/user/urls.py
- coldfront/core/user/views.py
- coldfront/static/core/user/js/registration.js
Fixes #53
Changes
- Added a view that returns whether a user with the given first and/or middle and/or last name exists.
- Added JavaScript code to make a request to the view when the user stops typing, and return the response.
- The middle name is not considered because the field may be empty for the existing user in the database.
> Give feedback if first/last names match existing user during registration

- coldfront/core/portal/templates/portal/allocation_by_fos.html
- coldfront/core/portal/templates/portal/center_summary.html
- coldfront/core/project/forms.py
- coldfront/core/project/templates/project/project_archive.html
- coldfront/core/project/templates/project/project_archived_list.html
- coldfront/core/project/templates/project/project_detail.html
- coldfront/core/project/templates/project/project_join_list.html
- coldfront/core/project/templates/project/project_list.html
- coldfront/core/project/templates/project/project_request/savio/project_request_card.html
- coldfront/core/project/templates/project/project_request/vector/project_request_card.html
- coldfront/core/user/templates/user/user_projects_managers.html
Continuing #57 
- updated `Field  of Science` -> `UCB Ccampus Division or Department` in frontend
- PIs cannot update project FOS
> refactor FOS -> UCB Campus Division or Department in UI

- coldfront/core/user/templates/user/login.html
- coldfront/static/core/user/css/login.css
login page, add space beneath `Forgot Your Password?`
> add bottom padding in login form

- coldfront/core/project/forms.py
- coldfront/core/project/templates/project/project_archive.html
- coldfront/core/project/templates/project/project_archived_list.html
- coldfront/core/project/templates/project/project_detail.html
- coldfront/core/project/templates/project/project_join_list.html
- coldfront/core/project/templates/project/project_list.html
- coldfront/core/project/templates/project/project_request/savio/project_request_card.html
- coldfront/core/project/templates/project/project_request/vector/project_request_card.html
- coldfront/core/project/views.py
- coldfront/core/user/templates/user/user_projects_managers.html
Refs #57
**Changes**
- Commented out places where the `FieldOfScience` is listed.
- Removed the field from the form for creating a new `Project`; the default `Other` is used.
> Hide Field of Science

- coldfront/core/project/templates/project/add_user_search_results.html
- coldfront/core/project/templates/project/project_add_users.html
- coldfront/core/user/forms.py
- coldfront/core/user/templates/user/user_access_agreement_form.html
Fixes #173, #174
**Changes**
- Hid the allocation selection form when adding a user to a project, since the user should be added to all them automatically.
- Reworded help text in form for adding users to a project to be more explicit about why some users cannot be selected.
- Moved the SU usage pop quiz question before the answer.
> Minor issue fixes

- coldfront/core/utils/management/commands/create_existing_brc_data.py
Fixes #176
**Changes**
- Modified `create_existing_brc_data` to create associations between the `abc` project and its users.
- Required a second password file `/tmp/passwd.abc`.
> Add support for loading abc users from the spreadsheet

- coldfront/core/user/templates/user/user_profile.html
> make alternative email status more intuitive

- coldfront/core/project/forms.py
Fixes #91
**Changes**
- Modified the help text for two questions.
- Removed a question.
> Make minor adjustments to survey questions for new Savio projects

- coldfront/core/user/forms.py
- coldfront/core/user/templates/user/user_list.html
- coldfront/core/user/urls.py
- coldfront/core/user/views.py
- coldfront/templates/common/navbar_admin.html
#201  : added admin view for listing all users
**discussion:**
- filtering through email needs to incorporate multiple email addresses?
- is this to replace `User Search` admin page
- incorporate more filters
> add admin view for searching through all users interactively

- coldfront/core/user/templates/user/user_profile.html
#214 
**NOTES:**
- added help text below the number as well
> add cluster-uid to the userprofile page

- coldfront/core/project/templates/project/project_join_list.html
as discussed in #217 
discussion:
- this looks clean, but it could be better?
> add project name in project join popup

- coldfront/core/allocation/templates/allocation/allocation_cluster_account_request_list.html
> add popup confirmation for denying cluster account requests

- bootstrap/ansible/main.copyme
- bootstrap/ansible/setup_cf_mybrc.yml
- coldfront/config/local_settings.py.sample
- coldfront/core/utils/management/commands/load_nodes.py
- coldfront/core/utils/management/commands/transform_jobs.py
This pull request merges cherry-picked commits from `develop` into `master`. In particular, it:
- Includes a missing script for loading `Nodes`,
- Enables the REST API by default in the Ansible setup,
- Correctly handles errors in a script for transforming old job data to new job data, and
- Separates API logs from portal logs.
> Fix various issues with allocations

- README.md
**Changes**
- Removed a JSON containing development data.
- Removed references to loading it in the documentation.
> Remove development data and relevant README instructions

- bootstrap/ansible/cf_mybrc_settings_template.tmpl
- bootstrap/ansible/main.copyme
- coldfront/config/local_settings.py.sample
- coldfront/core/project/utils.py
- coldfront/core/user/templates/user/user_profile.html
- coldfront/core/utils/mail.py
**Changes**
- Added a setting containing a list of admin email addresses to CC when request approval/denial emails are sent.
- Defined this setting in Ansible configuration.
- Corrected a bug in the User Profile wherein the current user's phone number and access agreement status appeared rather than the viewed user's.
- Corrected a bug causing `ProjectUser` creation to fail during project request approval.
> Minor bug fixes and enhancements

- bootstrap/ansible/cf_mybrc_settings_template.tmpl
- bootstrap/ansible/setup_cf_mybrc.yml
- coldfront/config/local_settings.py.sample
**Changes**
- Updated the Ansible playbook to copy `local_settings.py.sample` and `local_settings.py.sample` to the expected files.
- Updated the Ansible template for the deployment-specific settings file to include `LOG_PATH` and `API_LOG_PATH` constructed from variables in `main.yml`.
- Updated `local_settings.py.sample`:
- Removed extraneous variables and `print` statements.
- Updated `VECTOR_PI_USERNAME`.
- Updated the `LOGGING` dictionary to use updated paths imported from deployment-specific files.
- Suppressed a warning caused by using `is` with a string.
> Resolve issues with local settings

- coldfront/core/allocation/admin.py
> allow search on project name and title in admin/allocation/allocation

- coldfront/core/project/management/commands/get_survey_responses.py
- coldfront/core/project/tests/test_commands/test_get_survey_responses.py
> add get_survey_responses admin command

- coldfront/core/project/management/commands/add_service_units_to_project.py
- coldfront/core/project/tests/test_commands/test_add_service_units_to_project.py
-Added management command `add_service_units_to_project` in `coldfront/core/project/management/commands`
-Added tests in `coldfront/core/project/tests/test_commands/test_add_service_units_to_project.py`
> Issue 347 - add management command to add SUs back to project

- coldfront/core/project/management/commands/deactivate_ica_projects.py
- coldfront/core/project/management/commands/pending_join_request_reminder.py
- coldfront/core/project/models.py
- coldfront/core/project/tests/test_commands/test_deactivate_ica_projects.py
- coldfront/core/project/tests/test_commands/test_pending_auto_request_reminder.py
- coldfront/core/project/utils.py
- coldfront/core/project/utils_/email_utils.py
- coldfront/core/project/utils_/renewal_utils.py
- coldfront/templates/email/expired_ica_project.txt
merging branches 258 and develop to create common class for deactivate_ica_project and add_service_units_to_project
> merging branches 258 and develop

- coldfront/templates/common/authorized_navbar.html
- I removed the invoice section from the navbar
- moved jobs out of the project dropdown to its own tab
> Issue 369 - Remove Invoice from navbar and move jobs to separate tab

- coldfront/core/statistics/templates/job_detail.html
- coldfront/core/statistics/templates/job_list.html
Fixed small bug where the "Project" tab was active when viewing the Job list view or detail view
> Issue 373 - Job tab active status

- coldfront/core/allocation/admin.py
- fixed bug where allocation users were not searchable on project names
> allocation users now searchable on project name

- coldfront/core/project/forms.py
- coldfront/core/resource/utils.py
- altered get_compute_resource_names() to filter Resources with "Compute" in its name
- initializes cluster_name_choices for ProjectSearchForm in init function 
- Tested by creating new VM
> Issue 395 - VM installation error

- coldfront/core/project/templates/project/project_allocation_addition/request_card.html
- coldfront/core/project/templates/project/project_allocation_addition/request_list_table.html
- coldfront/core/project/templates/project/project_renewal/project_renewal_request_list_table.html
- coldfront/core/project/templates/project/project_renewal/request_card.html
- coldfront/core/project/templates/project/project_request/savio/project_request_list_table.html
- coldfront/core/project/templates/project/project_request/vector/project_request_list_table.html
fixes #376 
Edit: Missed the Detail Views, will add those changes tn.
> add direct project links to some request views

- coldfront/core/user/templates/user/user_profile.html
- coldfront/core/user/views.py
- Link Your Personal Account section in user profile is only visible to non LBL employees
- Removed section about LBL tokens
> Issue 383 - conditionally display account linking

- coldfront/api/billing/serializers.py
- coldfront/api/billing/tests/test_billing_activities.py
- coldfront/api/billing/tests/test_billing_base.py
- coldfront/api/billing/tests/utils.py
- coldfront/api/billing/urls.py
- coldfront/api/billing/views.py
- coldfront/api/urls.py
Fixes #462
**Changes**
- Added endpoints for listing and retrieving `BillingActivity` instances at `/api/billing_activities/` and `/api/billing_activities/{billing_activity_id}/`.
- Sample response for a single instance:
```
{
"id": 1,
"billing_project": "123456",
"identifier": "789"
}
```
- Added tests.
- Ensure that the API test suite is passing.
> Add REST API endpoints for BillingActivity

- requirements.txt
Changed Django-su version from 0.8.0 to 1.0.0 in requirements.txt
> Changed Django-su version in requirements.txt

- coldfront/api/user/serializers.py
- coldfront/config/local_settings.py.sample
- coldfront/config/test_settings.py.sample
- coldfront/core/allocation/tests/test_commands/test_start_allocation_period.py
- coldfront/core/utils/tests/test_export_data.py
- github/workflows/django_testing_ci.yml
This PR just includes some bug fixes in the testing suite and some added testing configuration sample files.
The bug fixes are needed so that the CI/CD tests don't fail for the wrong reasons.
`coldfront/config/test_settings.py.sample` will be used to generate a django configuration for automated testing.
The actual Github Actions workflow YAML file (https://github.com/Hzaakk/coldfront/blob/master/.github/workflows/django_testing_ci.yml) can be manually added in later to the master branch. I'm not sure if it makes any difference which branch the workflow file is located in, but I think putting it in master should be safe.
> Issue 304: Github Actions CI/CD changes

- coldfront/core/billing/management/commands/billing_ids.py
- coldfront/core/billing/tests/test_billing_base.py
- coldfront/core/billing/tests/test_commands/test_billing_ids.py
- coldfront/core/billing/tests/test_utils/test_billing_activity_managers.py
- coldfront/core/billing/utils/__init__.py
- coldfront/core/billing/utils/billing_activity_managers.py
- coldfront/core/billing/utils/queries.py
Fixes #465
**Changes**
- Added a `billling_ids` management command.
- Added initial subcommands:
1. `create`: Create `BillingActivity` objects.
2. `set`: Set `BillingActivity` objects for use as:
- `project_default`: A `Project`'s default billing ID,
- `recharge`: The billing ID to be used for the recharge usage fee for a `ProjectUser`, or
- `user_account`: the billing ID to be used for the user account fee for a `User`.
- By default, the validity of a billing ID is verified before creating/setting it. This may be bypassed using the `--ignore_invalid` flag.
- Updates may be staged using the `--dry_run` flag.
- Additional subcommands (e.g., `list`) may be added in the future.
- Added a set of manager classes that allow the billing ID for a particular database entity (e.g., `Project`, …
> Add command for creating/setting billing IDs and underlying manager classes

- coldfront/core/project/templates/project/project_request/savio/project_request_list.html
- coldfront/core/user/views.py
"Changed title: Savio to {{ PRIMARY_CLUSTER_NAME }}"
> Changed title: Savio to {{ PRIMARY_CLUSTER_NAME }}

- coldfront/core/user/views.py
Integrated feature flags for the EmailAddress variable based on LRC or BRC being active.
LRC uses allauth.account.models
BRC uses coldfront.core.user.models
> Added feature flags to the EmailAddress variable based on LRC or BRC

- coldfront/core/user/views.py
> Revert "Added feature flags to the EmailAddress variable based on LRC or BRC"

- coldfront/core/user/views.py
Added feature flags to EmailAddress model.
Created:  _filter_users_by_email()
> Added feature flags to EmailAddress model (WIP)

- coldfront/core/project/templates/project/project_detail.html
- coldfront/core/project/templates/project/project_request/savio/project_request_surveys_modal.html
- coldfront/core/project/views.py
> feat: add survey responses to Project detail view

- .env
- .gitignore
- README.md
**Changes**
- Rewrote and added detail to Docker setup instructions in `README.md`.
- Added `.env` to `.gitignore` so that user changes to it are not stored in VC. Updated instructions to have the developer create it.
- Included a step to build the new email image.
- Note any missing or unclear instructions.
> Update Docker README; ignore .env

- coldfront/templates/email/project_removal/project_removal.txt
Hi Wei, Matthew,
I added a small line to remind users to coordinate data backup/sharing with their group when they are leaving a project.
Is the wording okay?
Thanks,
Edison
> add reminder for user data sharing/backups

- bootstrap/ansible/playbook.yml
**Changes**
- Updated the Ansible playbook to install a dependency required by the Python package for validating LBL billing IDs in order to connect to LBL's Oracle database.
> Install dependency for package for validating LBL billing IDs

- bootstrap/ansible/main.copyme
- bootstrap/ansible/wsgi_conf_ssl.tmpl
**Changes**
- Updated settings to disable all django-debug-toolbar panels by default to avoid slowing down the development environment. Details: #553
- Updated the Ansible playbook to install a new Oracle dependency needed for the Python package for validating LBL billing IDs. Details: #554
> Fix connection to Oracle database for validating LBL billing IDs; improve dev environment performance

- coldfront/core/user/admin.py
- coldfront/core/utils/admin.py
**Changes**
- Updated the Django admin interface page for managing Users:
- Required that exactly one `EmailAddress` must be selected as the primary.
- Added a call to perform necessary processing when an address becomes the primary.
> Add constraints and processing to EmailAddress.primary checkboxes on User admin page

- coldfront/core/project/templates/project/project_request/savio/project_existing_pi.html
This PR isolates relevant changes from #613 by @jjung2-oxy.
> Provide clearer guidance for new project request PI selection step

- bootstrap/ansible/main.copyme
- bootstrap/ansible/settings_template.tmpl
- bootstrap/development/docker/README.md
- coldfront/config/local_settings.py.sample
- coldfront/config/test_settings.py.sample
- coldfront/core/project/tests/test_utils/test_new_project_user_utils/test_runners.py
- Moved `VECTOR_PI_USERNAME` and `SAVIO_PROJECT_FOR_VECTOR_USERS` settings out of `local_settings.py.sample` and into `settings_template.tmpl` such that they can be configured via YML variables.
- Updated the Docker `README` to discuss some use cases that may require `overrides.yml` to be specified in the Docker development environment, including these Vector-related YML variables.
**** Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration. …
> Allow Vector settings to be configured in YML

- coldfront/core/statistics/tests/test_job_views.py
- coldfront/core/statistics/utils_/job_query_filtering.py
include 'COMPLETED' jobs when searching for completing jobs
Fixes #481
Added a test case to TestSlurmJobListView
Strikethrough things that don’t make sense for your PR.
> Issue 481: include 'COMPLETED' jobs when searching for completing jobs

- coldfront/core/allocation/management/commands/data/brc_allocation_periods.json
- coldfront/core/allocation/management/commands/data/lrc_allocation_periods.json
- coldfront/core/utils/management/commands/data/brc_service_units.json
- coldfront/core/utils/management/commands/data/lrc_service_units.json
- Defined `AllocationPeriods` for the next year for BRC and LRC.
- Defined service units to be allocated under each period for BRC and LRC.
- Configuration update
**** Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration. ****
- Run the `create_allocation_periods` command to create the new periods. Verify that the periods are created, with correct dates, under `/admin` > `Allocation periods`.
- Instructional dates were parsed (by an LLM) …
> Define upcoming year's AllocationPeriods and SUs to allocate for them

- .github/workflows/django_testing_ci_python_3_13.yml
- Added a GitHub CI workflow YML for running tests on Python 3.13 when pushes and new/updated pull requests to the intermediate upgrade branch are made.
- New feature (non-breaking change which adds functionality)
**** Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant …
> [OS/Python Upgrade] Add GitHub workflow for running tests on Python 3.13 for changes to upgrade branch

- coldfront/api/allocation/tests/allocation_users/test_allocation_user_attribute_history.py
- coldfront/api/allocation/tests/allocation_users/test_allocation_user_attributes.py
- coldfront/api/allocation/tests/allocation_users/test_allocation_users.py
- coldfront/api/allocation/tests/allocations/test_allocation_attribute_history.py
- coldfront/api/allocation/tests/allocations/test_allocation_attributes.py
- coldfront/api/allocation/tests/allocations/test_allocations.py
- coldfront/api/billing/tests/test_billing_activities.py
- coldfront/api/statistics/tests/test_job_view_set.py
- coldfront/api/statistics/views.py
- coldfront/api/utils/tests/test_api_base.py
- coldfront/core/account/tests/test_utils/test_queries/test_update_user_primary_email_address.py
- coldfront/core/allocation/tests/test_commands/test_start_allocation_period.py
- coldfront/core/project/tests/test_views/test_project_removal_request_views.py
- coldfront/core/project/views_/new_project_views/request_views.py
- coldfront/core/project/views_/renewal_views/request_views.py
- coldfront/core/socialaccount/tests/test_cilogon_account_adapter.py
- coldfront/core/user/tests/test_views/test_activate_user_account.py
- coldfront/core/user/tests/test_views/test_link_login_views.py
- coldfront/core/utils/tests/test_export_data.py
- coldfront/templates/socialaccount/authentication_error.html
- coldfront/templates/socialaccount/connections.html
- coldfront/templates/socialaccount/login_cancelled.html
- Addressed test failures:
- Updated included template names used in `django-allauth` templates.
- Updated tests to reflect a change in the message returned by the REST API when a 404 is returned when retrieving an object. Instead of "Not found.", the message is now "No {ModelName} matches the given query." (This should not affect any existing clients, as far as is known.)
- Replaced a deprecated method for …
> [OS/Python Upgrade] Fix failing tests
