ucb-rit/coldfront

coldfront/core/project/forms.py, coldfront/core/project/templates/project/project_archived_list.html, coldfront/core/project/templates/project/project_join_list.html, coldfront/core/project/templates/project/project_list.html, coldfront/core/project/views.py
#36 
- clarified the meaning of `Lastname` and `Username` filter options in all Project search forms
- added option for case insensitive search on `Project.title` field in all Project search forms
- filtering on `Project.name` instead? (not displayed in list view)
=> fix #36: Improve project filtering in forms

coldfront/core/allocation/utils.py, coldfront/core/project/utils.py, coldfront/core/project/views.py
Fixes #71
**Changes**
- Added method for requesting cluster access for a user under a specific compute allocation for a project.
- Added logic to generate cluster access requests when:
- A user requests to join a project that does not require join approval,
- A manager of a project that requires join approval approves a request,
- A manager of a project changes the setting to no longer require join approvals, causing pending requests to be auto-approved.
=> Automatically request cluster access on approval of join request

coldfront/core/project/utils.py, coldfront/core/project/views.py, coldfront/core/user/utils.py, coldfront/templates/email/new_project_join_request_delay.txt, coldfront/templates/email/new_project_join_request_no_delay.txt
Refs #49
**Changes**
- Added logic to send an email to project managers, and PIs (who have notifications enabled), when a user requests to join.
- The email text differs based on whether the project has an auto-approval delay for joins.
- Fixed bug causing account activation email to fail.
=> Send notification email to managers when user joins

coldfront/core/portal/templates/portal/authorized_home.html, coldfront/core/portal/views.py, coldfront/core/project/forms.py, coldfront/core/project/utils.py, coldfront/core/project/views.py, coldfront/core/utils/management/commands/add_brc_accounting_defaults.py, coldfront/core/utils/management/commands/create_existing_brc_data.py, coldfront/core/utils/management/commands/load_brc_allocation_data.py
Fixes #84
**Changes**
- Added handling to create the "ABC Compute" `Resource`.
- Added a step to create the "abc" `Project` with the PI manually set.
- Added a step to create allocation-related objects for the "abc" `Project`, and refactored relevant code.
- Added filtering on cluster ABC when listing projects.
- Included ABC projects (i.e., just `abc`) for display on the home page.
- Run the following commands in order:
- `python manage.py add_brc_accounting_defaults` (creates "ABC Compute" `Resource`)
- `python manage.py create_existing_brc_data` (creates "abc" `Project`)
- `python manage.py load_brc_allocation_data` (sets up allocation-related objects for "abc" `Project`)
- Navigate to the list view for joining a project. Ensure that the "ABC" cluster …
=> Add support for ABC cluster/project

coldfront/core/project/templates/project/project_list.html
remove that weird "Name" `<tr>` from `project_list`
cant figure out how/when this got past us
=> remove weird "Name" on project_list.html

coldfront/core/portal/templates/portal/authorized_home.html, coldfront/core/project/templates/project/project_list.html, coldfront/core/project/utils.py, coldfront/core/project/views.py
Fixes #119
**Changes**
- Blocked access to the views for requesting a new project until the user has signed the access agreement.
- Automatically generated a cluster access request for the requester when the administrator fully approves the request.
=> Enforce that project requester is a manager with cluster access

coldfront/core/project/templates/project/project_join_list.html, coldfront/core/project/templates/project/project_request/savio/project_request_detail.html, coldfront/core/project/templates/project/project_request/vector/project_request_detail.html, coldfront/core/project/templates/project/project_review_join_requests.html, coldfront/core/project/templatetags/iso8601_to_datetime.py, coldfront/core/project/utils.py, coldfront/core/project/views.py, coldfront/templates/common/base.html
Fixes #93
**Changes**
- Specified timezone `America/Los_Angeles` in the base template, inherited by all other templates, so that all timestamps are displayed in that zone.
- Added a template tag that converts an ISO 8601-compliant string into a `datetime` object.
=> Display timestamps in America/Los_Angeles

coldfront/core/project/models.py, coldfront/core/project/templates/project/project_add_users.html, coldfront/core/project/utils.py, coldfront/core/project/views.py
Fixes #120
**Changes**
- Prevented users who are requesters or PIs on pending `Savio/VectorProjectAllocationRequests` from joining the project in question.
- Added `Project.save` to update any pending `ProjectUserJoinRequests` when a `Project`'s status changes to "Active" or "Denied".
- "Active": Only the latest join request is considered when auto-approving joins, so create a new object with the current time, so the delay begins now.
- "Denied": Deny any pending join requests.
- Only auto-approve join requests for "Active" projects.
=> Handle edge cases with joining pending projects

coldfront/core/project/forms.py, coldfront/core/project/templates/project/project_request/savio/project_existing_pi.html
Fixes #134
**Changes**
- Added a widget that allows specific options in a `Select` widget to be disabled.
- Used the widget in `SavioProjectExistingPIForm` so that PIs with existing FCAs/PCAs still appear, but cannot be selected.
- Updated help text.
=> Display PIs with FCAs/PCAs, but disallow selection

coldfront/core/utils/management/commands/load_brc_project_descriptions.py
Refs #57
**Changes**
- Added a management command for loading `Project` descriptions from existing spreadsheets.
- Criteria:
- The project name used in the database search is the value of the name column, converted to lower case and stripped of leading and trailing whitespace.
- Each row may correspond to an FCA and a Condo allocation, so both are updated.
- If a project is found multiple times, only the description of the first entry found is used.
- Run the command: `python manage.py load_brc_project_descriptions`.
**Notes**
- This command loads descriptions for 352/576 projects.
- This should only be run prior to going live, so that newly updated descriptions are not clobbered with old data.
=> Load project descriptions when possible

coldfront/core/user/templates/user/user_profile.html
make the `review and sign` button float right to better match the button styles on the page.
note:
- this will align with the phone number update button as well
new look:
=> float right for coherency in user profile

coldfront/config/local_settings.py.sample, coldfront/core/allocation/utils.py, coldfront/core/project/utils.py, coldfront/core/project/views.py
Fixes #117
**Changes**
- Added setting `SAVIO_PROJECT_FOR_VECTOR_USERS` with value `co_rosalind`. All Vector users are provided access to this project.
- Added logic to trigger: (a) adding a Vector user to the designated project, (b) requesting cluster access under it, and (c) sending an email to the user, when the following events occur:
- A request to create a new Vector project is approved. The user who created the request is the target user.
- A user's join request is approved (manually, via the cron job, when an admin manually checks for requests that have finished their delay period, and when a project's delay setting becomes 0).
- A user is manually added to a project by a manager.
- NOTE: If the user already has access to the Savio project, the logic is skipped.
- Refactored logic …
=> Automatically provide access to Savio for new Vector users

coldfront/core/portal/templates/portal/authorized_home.html, coldfront/core/project/templates/project/project_join_list.html, coldfront/core/project/templates/project/project_request/project_request.html, coldfront/core/user/forms.py, coldfront/core/user/templates/user/login.html, coldfront/core/user/templates/user/passwords/password_change_form.html, coldfront/core/user/templates/user/passwords/password_reset_complete.html, coldfront/core/user/templates/user/passwords/password_reset_confirm.html, coldfront/core/user/templates/user/passwords/password_reset_done.html, coldfront/core/user/templates/user/passwords/password_reset_email.html, coldfront/core/user/templates/user/passwords/password_reset_form.html, coldfront/core/user/views.py
Refs #127
**Changes**
- Added help text that the username is not the CalNet username, and that the password is not the CalNet password or the PIN + OTP combination.
- Added minimal help text explaining the relationship between projects and Slurm accounts.
=> Add clarifying help text about usernames, passwords, and projects

coldfront/core/project/templates/project/project_request/project_request.html, coldfront/core/project/templates/project/project_request/savio/project_request_landing.html, coldfront/core/project/templates/project/project_request/vector/project_request_landing.html, coldfront/core/project/urls.py, coldfront/core/project/utils.py, coldfront/core/project/views.py, coldfront/templates/email/project_request/pi_new_project_request.txt
Fixes #133
**Changes**
- Added a landing page for the new Savio project request form containing additional information.
- Added a landing page for the new Vector project request form containing additional information.
- Added logic to send an email to the PI for new Savio project requests when the requesting user is not the PI.
=> Clarify requester-related logic with landing pages; send email to PI when different from requester

coldfront/config/local_settings.py.sample, coldfront/config/settings.py, coldfront/config/urls.py
Fixes #155
**Changes**
- Moved REST API-related apps to the `EXTRA_APPS` variable in `local_settings.py` so that they can be enabled on a deployment-by-deployment basis.
- By default, it is disabled.
=> Allow REST API to be disabled

coldfront/core/allocation/views.py, coldfront/core/project/templates/project/project_detail.html, coldfront/templates/common/authorized_navbar.html
Fixes #165
**Changes**
- Removed the allocation-related section from the Project Detail view.
- Removed the "Allocations" and "User Allocations" links from the navigation bar.
- Limited access to the Allocation List and Detail views to superusers.
=> Hide main Allocation views

coldfront/core/user/templates/user/registration_form.html, coldfront/static/core/user/css/registration.css, coldfront/static/core/user/js/registration.js
Fixes #169
**Changes**
- Added logic to hide the registration button if the user's provided first and last name match those of an existing user. The user must then select a check box to acknowledge that they are a new user before the button re-appears.
- Run `python manage.py collectstatic` to update static files.
- Hard refresh any existing browser session.
=> Hide registration button if first/last name match

bootstrap/ansible/cf_mybrc_wsgi_conf_ssl.tmpl, bootstrap/ansible/main.copyme
**Changes**
- Filled in the production IP address in the sample `main.yml` file.
- Added redirection only when accessing port 80 via the external IP address, so that other services using the internal IP address are unaffected.
=> Only redirect port 80 to HTTPS if accessed via the external IP address

coldfront/core/project/utils.py, coldfront/core/project/views.py
Refs #49
**Changes**
- Replaced `EMAIL_TICKET_SYSTEM_ADDRESS` with `CENTER_HELP_EMAIL` (as the email address to contact) in the text of various emails.
=> Use CENTER_HELP_EMAIL instead of EMAIL_TICKET_SYSTEM_ADDRESS

bootstrap/ansible/cf_mybrc_wsgi_conf_ssl.tmpl
**Changes**
- Added a line to the template for the SSL WSGI configuration file that disables SSL v2 and v3 connections, which have security vulnerabilities.
=> Disallow SSL v2 and v3 connections

coldfront/core/project/templates/project/project_join_list.html
**Changes**
- Added the project's primary key to the `id` and other attributes of the reason modal for joining a project in order to disambiguate the modals.
- The issue was that they all had the same `id` (`reasonModal`). As a result, when clicking on a button to launch a modal for a particular project, the first one (corresponding to the first joinable project) always appeared.
=> Fix bug causing the wrong project to be joined

coldfront/core/project/utils.py, coldfront/core/user/forms.py, coldfront/core/user/templates/user/login.html, coldfront/core/user/templates/user/passwords/password_reset_done.html, coldfront/core/user/templates/user/user_reactivate.html, coldfront/core/user/urls.py, coldfront/core/user/utils.py, coldfront/core/user/views.py, coldfront/templates/email/account_already_active.txt, coldfront/templates/email/project_request/pi_new_project_request.txt
Fixes #193
**Changes**
- Included an account activation URL in the email notifying a newly-created PI user that someone has requested a new project under their name.
- Added a view where a user can provide their _primary_ email address to activate their portal account.
- If the account is already active, the email will say so.
- If not, an account activation URL will be included.
- The page itself will not provide any indication of the account's status, so email addresses and statuses will not be leaked.
- Added references to account reactivation in the login view and in the password reset view.
**Notes**
- Below are some implications of this functionality:
- Inactive users will always be able to make themselves active again. To prevent undesirable users from logging in, another setting …
=> Support account reactivation outside of the normal registration flow

coldfront/core/allocation/views.py
**Changes**
- Included `abc` as a `Project` to ignore when setting service units during cluster account activation, since they are irrelevant.
=> Ignore SU attribute setting for cluster accounts under "abc"

coldfront/core/project/utils.py
**Changes**
- Replaced `self.logger` with `logger` in code for approving a project request.
=> Remove reference to nonexistent logger

coldfront/api/statistics/utils.py, coldfront/core/allocation/utils.py, coldfront/core/project/utils.py
**Changes**
- Added logic to update "Service Units" amounts for existing users when a Savio pooling request is approved.
- Resolved issue in which `ProjectUser` `role` and `status` were not being set when the user was already a member of the `Project`.
- Added logic to set `Allocation` `start_date` and `end_date` during approval:
- `Savio`: Both dates are sent for FCAs and PCAs when pooling is not requested.
- `Vector`: The start date is always set. No end date is set.
=> Resolve issues with Savio project request approval

coldfront/core/project/templates/project/project_join_list.html, coldfront/core/project/views.py
**Fixes #260**
**Changes**
- Added text to the Project Join List view, explaining that project join requests are distinct from cluster access requests.
- Added a help icon and tooltip explaining the "Auto-Approval Time" column in the table.
- Blocked access to the view entirely for users who have not signed the access agreement.
=> Clarify what pending join requests are

coldfront/core/allocation/views.py
I looked into this and got a different error than what you described. I got the error 
```FieldError at /allocation/ Cannot resolve keyword 'username' into field. Choices are: allocationadminnote, allocationattribute, allocationuser, ...```
It was due to this query on line 414 of core/allocation/views.py:
```Q(username__icontains=data.get('username'))```
I changed it to
```Q(allocationuser__user__username__icontains=data.get('username'))```
Searching via usernames seems to work now.
=> issue_248: searching allocations on username error

coldfront/core/project/views.py
Fixes #284
**Changes**
- Removed a line that clobbered the value of a template variable, setting it to the incorrect queryset.
- The line was introduced when incorrectly resolving a merge conflict [here](https://github.com/ucb-rit/coldfront/pull/274/files#diff-cdebbdec350c291247bbd79c8fb68bd6f2b6318c10b9abc8374072378be7c14eR2513).
- Create some pending requests.
- Navigate to the list of pending requests.
- Ensure that sorting on individual columns behaves as expected.
=> fixed one line that got added by accident somehow

coldfront/templates/common/authorized_navbar.html, coldfront/templates/common/navbar_admin.html, coldfront/templates/common/navbar_nonadmin_staff.html
- Staff and admin drop down menus both now contain a submenu titled "Requests"
- Cluster Account Requests, Savio Project Requests, and Vector Project Requests are in the new submenu
- submenu is at the bottom of the original dropdown menu, separated by a divider
- is opened by hovering over "Requests"
- Other menu items were placed in alphabetical order above Requests
- "MyBRC Administration" Item in admin menu was kept at the top
=> Issue 282: Modifying Staff and Admin Dropdown menus

coldfront/core/allocation/views.py, coldfront/core/user/tests/test_views/test_staff_views.py, coldfront/core/utils/tests/test_staff_group.py
Added two test files to test staff group creation and staff group permissions:
-core/user/tests/test_views/test_staff_views.py
- tests accessing views that allow staff are supposed to be able to access
-core/utils/tests/test_staff_group.py
- tests that the staff group is created correctly
- tests that setting is_staff for a user adds/removes them from the staff group
=> Adding tests for staff group creation and permissions

coldfront/core/portal/templates/portal/authorized_home.html
Based on work by @Leon-Goldner-Cohen-Tzedek, from pull request #311.
**Fixes**
- Added a button to the home page that redirects to the view that lists all of the user's projects and their managers.
- The home page only lists active projects, while this view also includes inactive projects.
=> Add "View all projects and managers" button to home page

coldfront/core/user/templates/user/user_profile.html, coldfront/core/user/tests/test_views/test_identity_linking_request_view.py, coldfront/core/user/tests/test_views/test_user_profile/test_link_personal_account.py, coldfront/core/user/tests/utils.py, coldfront/core/user/views.py
Fixes #306
**Changes**
- Added text directing LBL users, who do not need to link an external identity, elsewhere.
- Disabled the button to request a linking email, and disabled access to the view, if the requesting user does not have active cluster access.
- Updated tests.
- Ensure that the following test suites pass:
```
python manage.py test coldfront.api.user.tests
python manage.py test coldfront.core.user.tests
```
- Ensure that the request button is disabled for a user without cluster access (i.e., any user whose username is an email address).
- Ensure that the request button is not disabled for a user with cluster access.
- Ensure that the new text makes sense.
=> Enhance "Link Your Personal Account" section of User Profile

coldfront/core/allocation/forms.py, coldfront/core/allocation/templates/allocation/allocation_update_cluster_account_status.html, coldfront/core/allocation/tests/test_views/test_allocation_cluster_account_activate_request_view.py, coldfront/core/allocation/tests/test_views/test_allocation_cluster_account_update_status_view.py, coldfront/core/allocation/views.py
**Changes**
- Added log messages to record the primary key of the superuser who updated the status of a cluster access request, for bookkeeping purposes.
- Fixed a bug in `AllocationRequestClusterAccountForm` which caused the status of "Pending - Add" requests to be changed to "Pending", causing them to disappear from the list view.
- Modified the button in `AllocationClusterAccountUpdateStatusView` to say "Update" instead of "Activate".
- Added tests.
- Ensure that the following test suite passes.
```
python manage.py test coldfront.core.allocation.tests
```
**Notes**
- Zero requests in production were affected by the above bug.
- Additional tests for these views should be written in the future.
=> Log which superuser updated a cluster account request; fix status bug

bootstrap/ansible/setup_cf_mybrc.yml, bootstrap/development/playbook.yml, coldfront/config/settings.py, coldfront/core/allocation/management/commands/create_allocation_periods.py, coldfront/core/project/utils.py, coldfront/core/utils/management/commands/add_lrc_accounting_defaults.py, coldfront/core/utils/management/commands/load_lrc_allocation_data.py
Fixes #324
**Changes**
- Added a management command that creates necessary database objects, like a `Resource` named "Lawrencium Compute" and an `AllocationAttributeType` named "Lawrencium Allocation Type".
- Added a management command that reads (a cleaned version of) `pca.conf` from the cluster, using the modification times and allocation amounts to create allocations for projects.
- The latest entry for a given project is used.
- Entries for PCAs are only included if they are on or after 2021/10/01 (the start of the current allocation year).
- Service Units are assigned as follows:
- Condo (`lr_`): The maximum number of SUs (effectively infinity).
- PCA (`pc_`) and Recharge (`ac_`): The allocation in CPU minutes divided by 60.
- Start Dates are set to the "modified time" in the file.
- …
=> Add commands for importing LRC allocation data

coldfront/core/project/utils.py, coldfront/templates/email/new_project_join_request.html, coldfront/templates/email/new_project_join_request.txt
Added a link to the email sent to PIs/managers that contains a link to approve/deny join requests. Also changed the wording of the email from "via MyBRC user portal" to "via the MyBRC User Portal".
=> Issue 330 - direct users to portal in email alert about new join requests 

coldfront/core/project/templates/project/project_renewal/new_project_details.html, coldfront/core/project/templates/project/project_renewal/new_project_survey.html, coldfront/core/project/templates/project/project_renewal/pi_selection.html, coldfront/core/project/templates/project/project_renewal/pooling_preference.html, coldfront/core/project/templates/project/project_renewal/project_selection.html, coldfront/core/project/templates/project/project_renewal/review_and_submit.html, coldfront/core/project/templates/project/project_request/savio/project_allocation_type.html, coldfront/core/project/templates/project/project_request/savio/project_details.html, coldfront/core/project/templates/project/project_request/savio/project_existing_pi.html, coldfront/core/project/templates/project/project_request/savio/project_ica_extra_fields.html, coldfront/core/project/templates/project/project_request/savio/project_new_pi.html, coldfront/core/project/templates/project/project_request/savio/project_pool_allocations.html, coldfront/core/project/templates/project/project_request/savio/project_pooled_project_selection.html, coldfront/core/project/templates/project/project_request/savio/project_recharge_extra_fields.html, coldfront/core/project/templates/project/project_request/savio/project_survey.html, coldfront/static/common/js/leave_form_alert.js, coldfront/templates/common/base.html
Fixes #190
Based on work by @jofeinstein and myself.
**Changes**
- Added JavaScript code to raise a warning when the user attempts to navigate away from/refresh/close a multi-part form.
- In particular, raise a warning if the form was modified, or if it is not the first form, even if it was unmodified.
- Included `jquery.dirty@0.8.3` as a dependency via CDN.
**Notes**
- Run the management command `collectstatic` in order for changes to take effect.
- The user could navigate back to the first form using the "First Step" and "Previous Step" buttons. Leaving at this point would cause future progress to be lost, but this seems rare.
=> Warn users before they can leave multi-part forms

README.md, coldfront/core/user/management/commands/set_passwords.py, requirements.txt
- added set_password management command in `core/user/management/commands/set_password.py`
- resolves [issue 341](https://github.com/ucb-rit/coldfront/issues/341)
- updated README.md. added additional step in "load database from dump file" section
- added tqdm to requirements.txt
=> Issue 341 - added set_password management command

coldfront/core/statistics/forms.py, coldfront/core/statistics/templates/job_list.html, coldfront/core/statistics/tests/test_job_views.py, coldfront/core/statistics/views.py
- Username search field only appears for PI/manager/staff/admin
- Now have a drop down select menu for Projects
- only projects that the user is an active member of appear
- can search incomplete project names such as "fc_" or click on project name in dropdown
- added to reset function to clear selectize values
- added tests to ensure username search field was properly popped
=> Enhance filtering in Job List view #350

coldfront/core/project/management/commands/add_service_units_to_project.py, coldfront/core/project/management/commands/deactivate_ica_projects.py, coldfront/core/project/management/commands/pending_join_request_reminder.py, coldfront/core/project/management/commands/utils.py, coldfront/core/project/models.py, coldfront/core/project/tests/test_commands/test_add_service_units_to_project.py, coldfront/core/project/tests/test_commands/test_deactivate_ica_projects.py, coldfront/core/project/tests/test_commands/test_pending_auto_request_reminder.py, coldfront/core/project/tests/test_commands/test_service_units_base.py, coldfront/core/project/utils.py, coldfront/core/project/utils_/addition_utils.py, coldfront/core/project/utils_/email_utils.py, coldfront/core/project/utils_/renewal_utils.py, coldfront/templates/email/expired_ica_project.txt
This is an extension of #357 by @jofeinstein.
Original PR text:
- created new management command `coldfront/core/project/management/commands/deactivate_ica_projects.py`
- added tests in `coldfront/core/project/tests/test_commands/test_deactivate_ica_projects.py`
- all tests pass on my setup
- Much of the code in `test_deactivate_ica_projects.py` is the same as code for `test_add_service_units_to_project.py` from [PR 355](https://github.com/ucb-rit/coldfront/pull/355). If we merge these branches, I can either create a new base class for both testing classes to inherit or have one of the testing classes inherit the other
=> Management command to deactivate expired ICA projects

README.md, requirements.txt
- added pylint and pylint-django to requirements.txt
- added documentation in the README about how to run pylint and pylint-django
- to install pylint and pylint-django, run `pip install -r requirements.txt`
- information on how to run pylint is in the README
=> Issue 377 pylint

coldfront/core/project/forms_/new_project_forms/request_forms.py, coldfront/core/project/templates/project/project_request/savio/project_existing_pi.html, coldfront/core/project/templates/project/project_request/savio/project_new_pi.html, coldfront/core/project/tests/test_forms/test_new_project_forms/test_savio_project_existing_pi_form.py
Addresses [issue 392](https://github.com/ucb-rit/coldfront/issues/392).
- Added validation to `SavioProjectNewPIForm` to enforce new PIs being lbl employees
- Added filtering to `SavioProjectExistingPIForm` to gray out users without an lbl email
- checks both primary email and any additional EmailAddresses associated with a user
- Added conditionally visible text to inform users of this in `savio/project_existing_pi.html` and `savio/project_new_pi.html`
=> added help text about lbl employees being PIs

coldfront/core/allocation/views.py, coldfront/templates/email/cluster_access_denied.txt
- altered the way emails are sent in AllocationClusterAccountDenyRequestView and AllocationClusterAccountActivateRequestView
- Managers and PIs (with notifications on) are cc'ed
- Addressed some confusion caused by ticket INC1369110
=> Cluster access emails now cc managers and PIs

coldfront/core/project/templates/project/project_request/savio/project_request_detail.html, coldfront/core/project/tests/test_views/test_new_project_views/test_savio_project_request_detail_view.py, coldfront/core/project/views_/new_project_views/approval_views.py, coldfront/core/project/views_/new_project_views/request_views.py
Fixes #404
**Changes**
- Adjusted new project request request/approval views to account for Condo and Recharge projects, which do not have `AllocationPeriods`:
- In `SavioProjectRequestWizard`, modified the method for retrieving the `AllocationPeriod` to return `None` if the request has no period.
- In `SavioProjectRequestDetailView`:
- Modified the method for determining whether the request's `AllocationPeriod` has started to return `True` if the request has no period.
- Displayed different status text for such requests.
- Added tests for checking the final processing logic for Condo and Recharge requests.
=> Remove assumptions that AllocationPeriod exists in new project request request/approval views

coldfront/api/utils/tests/test_api_base.py, coldfront/core/project/tests/test_utils/test_renewal_utils/test_allocation_renewal_processing_runner.py, coldfront/core/project/tests/test_utils/test_renewal_utils/utils.py, coldfront/core/utils/tests/test_base.py
**Changes**
- Overrode the `FLAGS` setting in test classes to disable `LRC_ONLY`. This is necessary because the `disable_flag` method does not successfully disable the flag, due to the fact that it is enabled directly in the setting.
- Fixed a test that was failing at certain times of day due to a lack of timezone conversion.
- Ensure that the test suite passes on an LRC-based VM.
**Notes**
- A longer-term solution is to define a `test_settings.py` module that can be set via `export DJANGO_SETTINGS_MODULE=path.to.test_settings` during tests.
=> Fix tests failures on LRC VMs caused by LRC_ONLY being enabled

coldfront/core/allocation/management/commands/create_allocation_periods.py, coldfront/core/project/templates/project/project_allocation_addition/request_card.html, coldfront/core/project/templates/project/project_allocation_addition/request_detail.html, coldfront/core/project/templates/project/project_renewal/project_renewal_request_detail.html, coldfront/core/project/templates/project/project_renewal/request_card.html, coldfront/core/project/templates/project/project_request/savio/project_request_card.html, coldfront/core/project/templates/project/project_request/savio/project_request_detail.html, coldfront/core/project/templates/project/project_request/vector/project_request_card.html, coldfront/core/project/templates/project/project_request/vector/project_request_detail.html
Moved status into "Request Information" section.
Specifically for: 
- Savio Project Request page
- Vector Project Request page
- Project Allocation Addition page
=> Moved status on Requests views into the 'Request Information' section.

coldfront/core/project/forms_/new_project_forms/request_forms.py, coldfront/core/project/tests/test_forms/test_new_project_forms/test_savio_project_survey_form.py
Refs #383
**Changes**
- Updated the survey form for new project requests to:
- Display text from variables instead of hard-coded strings, and
- Hide two fields ("data_storage_space", "cloud_computing") on LRC.
- Added tests.
- Ensure that the test suite passes.
- On a BRC/LRC VM, ensure that the correct text and fields appear.
- (Updating `FLAGS` manually in this case seems to cause the multi-part form (on my box, at least) to hang, so a properly-configured VM may be required.)
- Note any discrepancies.
- The form should also be rendered correctly in the approval view for the request.
**Notes**
- This branch depends on the `issue_414` branch.
=> Customize new project survey based on deployment

bootstrap/ansible/settings_template.tmpl, coldfront/core/portal/templates/portal/help.html
Refs #383
**Changes**
- Added a new dynamic setting `DOCS_GETTING_HELP_URL` that should point to:
- BRC: https://docs-research-it.berkeley.edu/services/high-performance-computing/getting-help/
- LRC: https://it.lbl.gov/resource/hpc/for-users/getting-help/
- Replaced BRC-specific help text with a sentence pointing the user to the URL.
- Re-run the Ansible playbook.
- At `/admin/constance/config/`, set `DOCS_GETTING_HELP_URL` to the appropriate one above.
- Navigate to the Help page (in the navbar), and ensure that the link behaves as expected.
=> Link to deployment-specific docs in Help/Contact page

coldfront/core/project/templates/project/project_join_list.html, coldfront/core/project/tests/test_utils/test_new_project_user_utils/test_runners.py, coldfront/core/project/tests/test_views/test_join_views/test_project_join_list_view.py, coldfront/core/project/utils_/new_project_user_utils.py, coldfront/core/project/views_/join_views/request_views.py, coldfront/core/user/utils_/host_user_utils.py
Fixes #448
**Changes**
- Updated the `needs_host` utility method to simply return whether the `User` has a `host_user`, so that even LBL employees may need a host (themselves).
- Rewrote logic for determining whether to ask the user to select a host when joining a project given this change.
- Updated logic for setting a host to set one for LBL employees who do not already have one (to themselves).
- Added and updated tests.
**Notes**
- The impetus for setting a host for LBL employees is that the LBL email address of the host is needed for all new cluster access requests, regardless of whether the user is an employee. Storing the host for all users simplifies the logic for determining the email address.
=> Also set host_user for LBL employees

coldfront/api/statistics/tests/test_can_submit_job.py, coldfront/api/statistics/views.py, coldfront/core/resource/utils.py
Fixes #446
**Changes**
- Added a utility method for returning a tuple of prefixes of names of `Projects` that have computing allowances.
- Updated `can_submit_job` to always allow jobs from `Projects` whose names do not start with these prefixes.
- Added a test.
=> Always allow jobs from departmental cluster projects

coldfront/core/allocation/management/commands/create_allocation_periods.py
**Changes**
- Updated `create_allocation_periods` to include entries for the following UC Berkeley semesters and summer sessions:
- Fall Semester 2022
- Spring Semester 2023
- Summer Sessions 2023 - Session A
- Summer Sessions 2023 - Session B
- Summer Sessions 2023 - Session C
- Summer Sessions 2023 - Session D
- Summer Sessions 2023 - Session E
- Summer Sessions 2023 - Session F
=> Create AllocationPeriods for UCB 2022-2023 Academic Year

coldfront/core/utils/management/commands/load_lrc_data.py
Fixes #447
**Changes**
- Added a subcommand to the `load_lrc_data` management command for setting the `UserProfile.host_user` field for existing `Users` in the database, using `usrdata_LRC` and a JSON mapping employee IDs of host users to details about those users (email address, full name).
- If a `User` object with the host email address can be found, set the user's host to the existing user.
- Otherwise, create a new `User` object and set the user's host to the newly-created user.
**Notes**
- The JSON is generated via an external script, using `usrdata_LRC` and the `ldapsearch` tool.
=> Add subcommand for loading in host users for existing users

bootstrap/ansible/main.copyme, bootstrap/ansible/playbook.yml, bootstrap/ansible/settings_template.tmpl, bootstrap/development/main.copyme, bootstrap/development/playbook.yml, coldfront/config/local_settings.py.sample, coldfront/core/billing/forms.py, coldfront/core/billing/models.py, coldfront/core/billing/utils/queries.py, coldfront/core/billing/utils/validation/__init__.py, coldfront/core/billing/utils/validation/backends/base.py, coldfront/core/billing/utils/validation/backends/dummy.py, coldfront/core/billing/utils/validation/backends/oracle.py, coldfront/core/project/tests/test_views/test_new_project_views/test_savio_project_request_wizard.py, coldfront/core/project/views_/new_project_views/request_views.py
Fixes #467
**Changes**
- Updated Ansible configuration so that a Python package for validating LBL billing IDs may be installed only when needed.
- It is only intended to be installed on LRC deployments that have access to the Oracle database.
- In other cases, nothing needs to be done.
- Introduced a billing `validation` module (modeled after `django.core.mail`):
- Introduced a set of billing validator backends that can be used to determine whether a billing ID is currently valid.
- `OracleValidatorBackend` uses the Python package, which connects to Oracle to determine the answer.
- This backend should not be imported if the Python package is not installed, as an `ImportError` will be raised.
- `DummyValidatorBackend` returns whether the last digit of the ID is even.
- Added a …
=> Conditionally use Python package for validating LRC billing IDs

bootstrap/ansible/main.copyme, bootstrap/ansible/settings_template.tmpl, bootstrap/development/main.copyme, coldfront/config/local_settings.py.sample
**Changes**
- Moved the following variables out of `local_settings.py.sample` and into the Ansible settings template:
- `CENTER_USER_GUIDE`
- `CENTER_LOGIN_GUIDE`
- `CENTER_HELP_EMAIL`
- Listed values to use for BRC and LRC in the settings template.
- Copy the new Ansible variables in `main.copyme` to `main.yml`, setting the appropriate values for the instance.
- Re-run the Ansible playbook.
- Ensure that the settings are empty in the generated `local_settings.py`.
- Ensure that the settings match the Ansible variables in the generated `dev_settings.py`.
- In the shell, ensure that the settings match the Ansible variables:
```python
from django.conf import settings
>>> settings.CENTER_USER_GUIDE
''  # …
```
=> Configure additional CENTER_* settings in Ansible

bootstrap/ansible/main.copyme, bootstrap/ansible/settings_template.tmpl, bootstrap/development/main.copyme, coldfront/config/settings.py
**Changes**
- Updated Ansible configuration to allow `ALLOW_ALL_JOBS` to be set to `True` in the generated settings file.
- Set `allow_all_jobs` to `true`/`false` in `main.yml`.
- Ensure that the generated settings file is updated accordingly when the playbook is run.
- Ensure that the correct settings file is observed in the shell.
=> Allow ALLOW_ALL_JOBS to be configured in Ansible

coldfront/api/user/serializers.py
**Changes**
- Wrapped the usage of `UserProfileSerializer` in a `SerializerMethodField` so that the serializer is not instantiated during application initialization.
- The instantiation is problematic during initial setup (e.g., the first invocation of `migrate`) because `UserProfileSerializer.__init__` calls `flag_enabled`, which depends on the table `flags_flagstate` existing, but the table does not exist until `migrate` has been called.
**Notes**
- This is similar to #395.
=> Avoid instantiating UserProfileSerializer in class attribute of UserSerializer

coldfront/api/permissions.py, coldfront/api/statistics/tests/test_job_view_set.py, coldfront/api/statistics/views.py, coldfront/api/utils/urls.py
**Changes**
- Updated API permission classes to inherit from `IsAuthenticated` so that all views using them require that the user be authenticated (e.g., by giving an API token).
- Added a note to `can_submit_job` explaining that it uses the default permission class.
- Added and updated tests.
- Ensure that the API tests, which already test authorization for varyingly privileged users, pass.
=> Require authentication for all endpoints

bootstrap/ansible/main.copyme, bootstrap/ansible/playbook.yml, bootstrap/ansible/wsgi_conf_ssl.tmpl
**Changes**
- Added Cloudflare-related Ansible settings:
- When Cloudflare is enabled (LRC production only at the moment):
- Update `firewalld`,
- Update the Apache `LogFormat` so that the original IP address of the client (not a Cloudflare IP address) is logged,
- Restrict access to the web server to a pre-defined set of IP addresses, and
- Update the name of the server in Apache.
- Made the SSL certificate chain file optional.
- Allowed the list of IP ranges that have access to the API to be empty.
- Update `main.yml` to reflect the changes to `main.copyme`.
- Re-run the Ansible playbook, noting any issues.
**Notes**
- This has been tested on both …
=> Configure Apache based on whether Cloudflare is enabled/disabled; clean up playbook

README.md, bootstrap/ansible/main.copyme, bootstrap/ansible/settings_template.tmpl, coldfront/config/test_settings.py.sample
**Changes**
- Added an Ansible setting `email_admin_list` that becomes the value of the Django setting `EMAIL_ADMIN_LIST`.
- If the provided list is empty, the value is set to the previous default.
- Removed a hard-coded email address in favor of setting addresses on a case-by-case basis.
- Update `main.yml` to reflect the changes to `main.copyme`.
- Re-run the Ansible playbook, noting any issues.
- In the Django shell, ensure that `EMAIL_ADMIN_LIST` has the correct value (either the user-specified list, or the previous default if the former is empty).
=> Allow EMAIL_ADMIN_LIST to be configured in Ansible

coldfront/api/allocation/tests/allocation_users/test_allocation_users.py, coldfront/api/allocation/tests/allocations/test_allocations.py, coldfront/api/allocation/tests/allocations/test_cluster_access_requests.py, coldfront/api/allocation/tests/test_allocation_base.py, coldfront/api/statistics/tests/test_job_view_set.py, coldfront/core/allocation/utils.py, coldfront/core/project/management/commands/projects.py, coldfront/core/project/tests/test_utils/test_project_removal_request_runners.py, coldfront/core/project/tests/test_utils/test_renewal_utils/test_allocation_renewal_approval_runner.py, coldfront/core/project/tests/test_utils/test_renewal_utils/test_allocation_renewal_denial_runner.py, coldfront/core/project/tests/test_utils/test_renewal_utils/test_allocation_renewal_processing_runner.py, coldfront/core/project/tests/test_utils/test_renewal_utils/utils.py, coldfront/core/user/tests/test_views/test_request_hub_view.py, coldfront/core/utils/management/commands/add_accounting_defaults.py, coldfront/core/utils/tests/test_export_data.py
Fixes #496
**Changes**
- Updated the list of compute-related `Resources` to be created to include an entry for the new savio4_refmlab cluster.
- Modified the function for getting the name of the compute-related `Resource` for a particular `Project` to be more general.
- Added a management command `projects` with a `create` subcommand that allows a `Project` for a standalone cluster (e.g., savio4_refmlab) to be created.
- The subcommand can be generalized in the future, and additional subcommands can be added.
=> Introduce savio4_refmlab cluster; add command for creating standalone cluster project

coldfront/core/billing/tests/test_utils/test_validation_backends.py, coldfront/core/billing/utils/validation/backends/permissive.py
**Changes**
- Added a new billing validator backend `PermissiveValidatorBackend` that returns `True` for all billing IDs.
- The setting `BILLING_VALIDATOR_BACKEND` can be set to this in case the production backend fails or is inaccessible.
- Caveat: Invalid billing IDs will be allowed.
- Added tests for `DummyValidatorBackend` and `PermissiveValidatorBackend`.
=> Add billing validator backend that allows all billing IDs

bootstrap/ansible/playbook.yml
**Changes**
- Updated the Ansible playbook so that:
- Services are "started" or "reloaded" instead of "restarted" so that they can continue to handle requests during non-provisioning playbook runs.
- All critical services are enabled (either during provisioning or common tasks).
=> Avoid restarting services during playbook "common tasks"; enable critical services

coldfront/core/project/templates/project/project_detail.html
Cherry picked from #504, by @jjung2-oxy.
**Changes**
- Removed the edit icon next to the "Requests to Join" section of the Project Detail View, since there is already an "Update Project Information" button that does the same thing.
- Ensure that the icon is no longer there.
=> Remove edit icon from Project Detail View

.github/workflows/django_testing_ci.yml, README.md, Vagrantfile, bootstrap/ansible/playbook.yml, bootstrap/ansible/requirements.yml, bootstrap/development/load_database_backup.sh
Upgraded postgres version to 15.
Removed all hardcoded python and postgres versions in ansible playbook with variables
Some QOL stuff added to .bashrc by ansible
Notes (I have no idea why the following 2 are the case):
The 'Upgrade pip' task isn't needed with python 3.8
When upgrading to python 3.8 via SCL, the following has to be added to the 'install django application dependencies' task:
`environment: # needed as pg_config isn't in PATH by default
PATH: "{{ ansible_env.PATH }}:/usr/pgsql-{{ postgres_version }}/bin"`
@matthew-li also made the following changes:
- Incorporated @Hzaakk's Postgres-related changes from #493.
- Removed Ansible tasks to change the Postgres authentication method from `ident` to `md5`, since Postgres now uses `scram-sha-256` by default.
- Note: When upgrading a …
=> Issue 494: Upgrading Postgres 9.6 -> 15

coldfront/config/urls.py, coldfront/core/allocation/views.py, coldfront/core/allocation/views_/cluster_access_views.py, coldfront/core/allocation/views_/secure_dir_views.py, coldfront/core/grant/views.py, coldfront/core/project/views.py, coldfront/core/project/views_/addition_views/approval_views.py, coldfront/core/project/views_/addition_views/request_views.py, coldfront/core/project/views_/join_views/request_views.py, coldfront/core/project/views_/new_project_views/approval_views.py, coldfront/core/project/views_/new_project_views/request_views.py, coldfront/core/project/views_/removal_views.py, coldfront/core/project/views_/renewal_views/approval_views.py, coldfront/core/statistics/views.py, coldfront/core/user/views.py
Fixes #406
**Changes**
- Updated the login view:
- If the user is already authenticated, redirect to the provided `next` URL (or the home page).
- Otherwise, redirect to the Basic Auth. or SSO login page, propagating the provided `next` URL so that the user is redirected there after login.
- Removed `login_url` across all views, so that unauthenticated users are always redirected to the login view, with `next` set to the view.
- This has been deployed to the staging servers.
=> Ensure users are directed to the correct page after clicking on a link and having to login

coldfront/core/project/views_/renewal_views/approval_views.py
Fixes #517
**Changes**
- Updated the method for getting the amount of SUs to allocate to a renewed project to only perform prorating for allowances to which prorating is applicable.
- This resolves the issue with ICA renewals (generated on the back end) on MyBRC showing the wrong amount.
- When ICA and PCA renewals on MyBRC are formally supported on the front end, the correct amount will be set in any created request (it would not have been prior to this change).
=> Display correct SU amount on renewal request detail page for all allowance types

coldfront/core/allocation/management/commands/approve_renewal_requests_for_allocation_period.py, coldfront/core/allocation/management/commands/create_allocation_periods.py, coldfront/core/allocation/management/commands/data/brc_allocation_periods.json, coldfront/core/allocation/management/commands/data/lrc_allocation_periods.json, coldfront/core/allocation/management/commands/start_allocation_period.py
**Changes**
- Added a `--skip_emails` flag to the `approve_renewal_requests_for_allocation_period` and `start_allocation_period` management commands for testing the commands without sending emails.
- Updated the `create_allocation_period` management command to load period data from a pre-defined file, and added upcoming BRC and LRC periods.
=> Allow emails to be skipped during request approval/processing; load allocation periods from file

coldfront/core/portal/templates/portal/nonauthorized_home.html
**Changes**
- Updated the "CalNet: Log In" button on the home page of MyBRC to redirect to CILogon with the "University of California, Berkeley" provider selected, not the "Lawrence Berkeley National Laboratory" provider.
=> Fix "CalNet: Log In" button destination

coldfront/core/socialaccount/adapter.py, coldfront/core/socialaccount/signals.py, coldfront/core/socialaccount/tests/test_cilogon_account_adapter.py
Refs #544
**Context**
- A Berkeley user may have both a base `@berkeley.edu` email address and a departmental email address.
- Consider a pre-existing portal user who:
- Has a base `@berkeley.edu` email address associated with their portal account,
- Has since added a departmental email address to their Berkeley account (not portal account), and
- Has never logged in via CILogon (so does not have an existing `SocialAccount` object).
- When the user logs in via CalNet, CILogon provides the departmental address as the email. The system fails to look up a user with a matching `EmailAddress`, so it creates a new portal account, rather than connecting the user to their existing portal account.
- This pull request uses the fact that CILogon also provides an `eppn` field containing the base …
=> Consider eppn field when identifying users during CILogon auth; refactor and add tests for auth logic

bootstrap/ansible/main.copyme, bootstrap/ansible/playbook.yml
**Changes**
- Adjusted Systemd behavior for Supervisor, via a drop-in file, so that it stops managed workers when stopped, reloads them when reloaded, and always restarts.
- In development environments, ensured that Supervisor only comes up after the repository has been mounted.
- Adjusted Supervisor configuration for `django_q` so that it always restarts.
- Add the new Ansible variable to `main.yml`.
- Re-run the Ansible playbook.
- Stop and restart the VM. Ensure that Supervisor and the processes it manages are up.
- Stop Supervisor and ensure that its managed processes are also stopped.
=> Ensure that Supervisor and managed processes come up on boot and restart automatically

bootstrap/ansible/settings_template.tmpl
Basically unchecking the toolbar panels by default. Performance is bad when they're on, so it helps if we can only turn the panels on when needed.
=> Disable Django Debug Toolbar panels by default

coldfront/core/project/utils.py, coldfront/core/user/management/commands/merge_users.py, coldfront/core/user/utils_/merge_users/__init__.py, coldfront/core/user/utils_/merge_users/class_handlers.py, coldfront/core/user/utils_/merge_users/runner.py, coldfront/core/user/utils_/user_merge_utils.py, coldfront/core/utils/reporting/report_message_strategy.py
Refs #544
**Changes**
- Added a management command `merge_users` for merging a source `User` into a destination `User`, based on whichever has cluster access.
- It currently only handles a subset of cases, but can be expanded as needed. Notably, it does not handle:
- Two users who both have cluster access,
- Source users who have non-compute `Allocations`,
- LRC users.
- This has been manually tested on staging.
=> Add rudimentary command-line tool for merging two users

coldfront/core/billing/management/commands/billing_ids.py, coldfront/core/billing/tests/test_commands/test_billing_ids.py, coldfront/core/billing/utils/queries.py
**Changes**
- Added a `list` subcommand to the `billing_ids` command that allows listing of all billing IDs matching the following filters (which may be combined):
- Specific billing ID (e.g., `list --billing_id 123456-789`): List all usages of `123456-789`.
- Specific project (e.g., `list --project_name project_name`): List all billing IDs associated with the project `project_name` (the project default ID and recharge IDs).
- Specific user (e.g., `list --username username`): List all billing IDs associated with the user `username` (recharge IDs and user account IDs).
- Added a helper query method to support the subcommand (and, in the future, a way to list this information from the UI).
**Notes**
- Tests for the `list` subcommand remain to be written.
=> Enable listing of billing IDs from the command-line

coldfront/core/allocation/admin.py, coldfront/core/project/admin.py, coldfront/core/statistics/admin.py, coldfront/core/user/admin.py
Added admin.site.register(<model_name>) for any missing models on the admin site.
=> Registered Django admin pages for models that don't have them

coldfront/config/urls.py, coldfront/core/billing/forms.py, coldfront/core/billing/templates/billing/billing_id_usages_search.html, coldfront/core/billing/urls.py, coldfront/core/billing/views/admin_views.py, coldfront/core/project/urls.py, coldfront/templates/common/navbar_admin.html, coldfront/templates/common/navbar_nonadmin_staff.html
**Changes**
- Added an admin view (Admin > LBL Project IDs) for listing usages of billing IDs, with logic identical to the `list` subcommand of `billing_ids` described in #559.
- The view is also accessible to staff (Staff > LBL Project IDs), but not regular users.
=> Add admin-only view for listing usages of billing IDs

coldfront/core/allocation/forms_/secure_dir_forms.py, coldfront/core/allocation/templates/secure_dir/secure_dir_request/directory_name.html, coldfront/core/allocation/templates/secure_dir/secure_dir_request/secure_dir_request_card.html, coldfront/core/allocation/tests/test_utils/test_secure_dir_utils.py, coldfront/core/allocation/tests/test_views/test_secure_dir_request_views.py, coldfront/core/allocation/utils_/secure_dir_utils.py, coldfront/core/allocation/views_/secure_dir_views.py
**Changes**
- Updated the forms for requesting a new secure directory and for updating a secure directory's name during review to allow the user to provide a name that either has or does not have the expected prefix (`pl1_`). This prevents a name from being displayed erroneously (e.g., `pl1_pl1_name`).
- Updated the corresponding views to store the directory name in `SecureDirRequest` with the prefix included.
- Updated views and templates to avoid prepending the prefix given that it is now stored.
- Updated tests.
=> Clean user-provided secure directory name

bootstrap/ansible/logrotate.tmpl, bootstrap/ansible/main.copyme, bootstrap/ansible/playbook.yml
**Changes**
- Updated the Ansible playbook to configure `logrotate` to rotate the API and portal logs during provisioning.
- Each log will be rotated weekly, with the last eight files kept. Rotated files, except the most recent one, are compressed.
- Each rotated file has the date appended, along with the UNIX timestamp to avoid conflicts.
**Notes**
- A separate script is needed to archive the rotated, compressed files before `logrotate` deletes them.
=> Configure logrotate for API + portal logs during Ansible provisioning

bootstrap/ansible/main.copyme, bootstrap/ansible/playbook.yml
**Changes**
- Added an Ansible task to install a cron job to back up rotated log files to a designated directory.
- The job is only installed if an existent directory is given via the variable `log_backup_dir_path`.
- The job is configured to run at the first minute on the 15th day of each month.
- Given that rotated files are kept in the log directory for 8 weeks, no log should be deleted before it is successfully backed up.
=> Configure optional cron job to backup rotated log files

coldfront/core/allocation/management/commands/correct_user_service_units.py, coldfront/core/allocation/tests/test_utils/test_cluster_access_runners.py, coldfront/core/allocation/utils_/accounting_utils.py, coldfront/core/allocation/utils_/cluster_access_utils.py, coldfront/core/utils/management/commands/load_lrc_data.py
Refs #574
**Changes**
- Updated the condition under which the "Service Units" `AllocationUserAttribute` is set when processing a cluster access request.
- From: "when the project belongs to the 'primary' cluster"
- To: "when the project `Allocation` has a 'Service Units' `AllocationAttribute`"
- Added a command `correct_user_service_units` to create/update "Service Units" `AllocationUserAttributes` to match the corresponding `AllocationAttribute`.
=> Correct bug causing "Service Units" AllocationUserAttribute to not be set for some LRC projects; add correction command

coldfront/core/billing/management/commands/billing_ids.py, coldfront/core/billing/views/admin_views.py
**Changes**
- Updated the admin view for listing billing IDs and the `billing_ids` command to avoid listing recharge billing IDs if the corresponding user does not have one of the following statuses on the corresponding project: "Active", "Pending - Add", "Pending - Remove".
- Currently, that means that users with the following statuses are excluded: "Denied", "Removed".
=> Exclude project-specific billing IDs if user has irrelevant status on project

coldfront/core/utils/tests/test_export_data.py
**Changes**
- Added `TestRenewalSurveyResponses` in `coldfront.core.utils.tests.test_export_data.py`
- 3 tests: JSON, CSV, allowance type
- Uses the following hardcoded elements:
- Hardcoded renewal survey with sample answers for BRC version of `ProjectRenewalSurveyForm`
- `Allowance Year 2024 - 2025`
- CSV test uses question 6 from the renewal survey
**Testing**
- Within `app-shell`, run the following: `python3 manage.py test coldfront.core.utils.tests.test_export_data.TestRenewalSurveyResponses`
=> Adding unit testing for export_data renewal_survey_answers command

coldfront/core/allocation/management/commands/data/brc_allocation_periods.json, coldfront/core/allocation/management/commands/data/lrc_allocation_periods.json
**Changes**
- Added `AllocationPeriod` entries:
- For "Allowance Year 2025 - 2026" for BRC and LRC.
- For UC Berkeley [Academic Calendar](https://registrar.berkeley.edu/wp-content/uploads/UCB_AcademicCalendar_2024-25.pdf) semesters and summer sessions for BRC.
- Ensure that the test suite passes.
- In particular, double-check the dates against the calendar linked above.
- For both BRC and LRC:
- Run `python manage.py create_allocation_periods --dry_run` and ensure that the new periods are listed.
- Re-run it without the dry run flag and ensure that the new periods are created.
- Note: They should not appear in the new project request or renewal request flows.
=> Add AY25-26 periods for BRC/LRC; add UCB 2024-25 calendar periods

coldfront/core/allocation/templates/allocation/allocation_detail.html, coldfront/core/allocation/utils.py, coldfront/core/allocation/views.py
**Changes**
- Adds a pie chart that displays the SU usage broken down by user. Hovering over a slice brings up the username, used SUs, and percentage of total used for users with positive SU usage.
- Added function in `allocation/utils.py` to generate the pie chart data.
- New `context_data` attribute for `pie_data` in `allocation/views.py`.
- New `drawPies` function in `allocation_detail.html` draws the pie chart, which is inserted right under the existing "Service Units" gauge graph.
- Legend appears to the right of the pie chart in columns.
- When there are no users with non-zero usage, displays a message indicating there is no data available.
**Testing**
- Manual testing can be done by navigating to any project's Allocation Detail page and ensuring things look okay. Good examples …
=> Issue 602: Add diagram to display SU usage by user on Allocation Detail page

coldfront/core/allocation/tests/test_commands/test_start_allocation_period.py, coldfront/core/project/tests/test_views/test_renewal_views/test_allocation_renewal_request_under_project_view.py, coldfront/core/project/tests/test_views/test_renewal_views/test_allocation_renewal_request_view.py, coldfront/core/utils/management/commands/data/brc_service_units.json, coldfront/core/utils/management/commands/data/lrc_service_units.json
**Changes**
- Updated the JSONs used to created `TimedResourceAttributes` for service units amounts for "Allowance Year 2025 - 2026".
- Corrected a bug in `test_start_allocation_period` causing an Allowance Year period to be detected as an instructional period.
- Removed testing of "Allowance Year 2023 - 2024" from the tests for whether the renewal survey appears, since that period may no longer be selected.
- Note: These tests, and the functionality they test, must still be updated to remove the hard-coded period.
=> Add SU amounts for the next allowance year; fix test bugs relating to transition to new allowance year

coldfront/core/allocation/management/commands/data/brc_allocation_periods.json, coldfront/core/utils/management/commands/data/brc_service_units.json
**Context**
- The form for requesting a new project with the computing allowance "Instructional Computing Allowance" is failing on MyBRC.
- The form for selecting the allocation period is raising an error. Each period has a number of service units to be granted with it, and that number is pulled from the database for display, but the number was not defined for some of the options, leading to an error.
**Changes**
- Defined the number of SUs to be granted for missing allocation periods in the JSON file read by the `add_allowance_defaults` command, which will need to be run to fill in the missing values.
**Notes**
- Consider how this can be avoided in the future.
=> Define SUs for ICAs periods for UCB Academic Year 24-25

.gitignore, coldfront/core/allocation/forms.py, coldfront/core/allocation/utils.py, coldfront/core/project/forms_/new_project_forms/request_forms.py, coldfront/core/project/management/commands/projects.py, coldfront/core/project/tests/test_commands/test_deactivate_ica_projects.py, coldfront/core/project/tests/test_commands/test_ica_renewal.py, coldfront/core/project/tests/test_commands/test_projects.py, coldfront/core/project/utils_/renewal_utils.py, coldfront/core/project/views_/new_project_views/approval_views.py, coldfront/core/project/views_/renewal_views/approval_views.py, coldfront/core/resource/utils_/allowance_utils/computing_allowance.py
Based off code from @matthew-li 
- This PR contains updated `projects` command-line tool (`coldfront.core.project.management.commands.projects`) to enable renewal of ICA projects that have the "Inactive" status.
- Added a subcommand `renew` by which this can be done.
- It takes arguments: the name of the `Project`, the username of the `User` making the request, and the name of the `AllocationPeriod` the allowance will be valid for.
- It will approve and process the request. I will provide you with some example code I've run manually in the past that should be adapted into this command.
- Disallow renewals of other project types at this point (so only ICAs).
- There should be a `dry_run` flag (see the `create` subcommand).
Assumptions made:
- I assumed that the pre-project and post-project …
=> Issue 51: Method for renewing Instructional Computing Allowances (ICAs)

bootstrap/development/docker/README.md, bootstrap/development/docker/images/app-base.Dockerfile, bootstrap/development/docker/images/app-config.Dockerfile, bootstrap/development/docker/images/db-postgres-shell.Dockerfile, bootstrap/development/docker/images/os.Dockerfile, bootstrap/development/docker/scripts/build_images.sh
**Changes**
- Changed the underlying base Docker image from `ubuntu:latest` to `rockylinux:8.8`.
- Installed Python 3.10 from source to avoid differences between e.g., Intel and Apple Silicon, as well as incompatibilities caused by later versions of Python (e.g., 3.12).
- Moved dependency installation (including Python) into a new base image `os`, inherited by `app-base` and `app-config`.
- Updated the Docker `README.md` to note that an error may arise during the database load, but is not an issue.
- Ensure that the Docker build succeeds on both Intel (tested by me) and Apple Silicon.
- Ensure that the development environment instructions work from beginning to end.
=> Docker dev. env: Switch to Rocky 8.8; lock Python 3.10

bootstrap/development/docker/README.md, bootstrap/development/docker/images/app-base.Dockerfile, bootstrap/development/docker/images/app-config.Dockerfile, bootstrap/development/docker/images/db-postgres-shell.Dockerfile, bootstrap/development/docker/images/os.Dockerfile, bootstrap/development/docker/scripts/build_images.sh, bootstrap/development/docker/scripts/create_env_file.sh, bootstrap/development/docker/scripts/docker_generate_secrets.sh, bootstrap/development/docker/scripts/docker_generate_settings.sh
**Context**
- The Ubuntu Docker image pulled for Apple Silicon appears to have adopted [PEP 668](https://peps.python.org/pep-0668/), producing the below error when attempting to install Pip requirements in the absence of a virtual environment.
```
error: externally-managed-environment
× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
python3-xyz, where xyz is the package you are trying to
install.
If you wish to install a non-Debian-packaged Python package,
create a virtual environment using python3 -m venv path/to/venv.
Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
sure you have python3-full installed.
If you wish to install a non-Debian packaged Python application,
it may be easiest to use pipx install xyz, which will …
```
=> Install Python dependencies in virtual environment in Docker images to satisfy PEP 668; replace apt-get with apt

bootstrap/development/docker/README.md, bootstrap/development/docker/scripts/docker_load_database_backup.sh, bootstrap/development/docker/scripts/docker_run_django_scripts.sh
**Context**
- Docker Desktop v4.32.0 retired the `docker-compose` binary for macOS ([release notes](https://docs.docker.com/desktop/release-notes/#for-mac-2)).
**Changes**
- Replaced calls to the binary with `docker compose` in Docker development environment scripts and documentation.
- Ensure that the application stack can be started and that scripts (e.g., `docker_run_django_scripts.sh`) behave as before.
=> Replace 'docker-compose' binary with 'docker compose' in Docker environment

coldfront/config/settings.py, coldfront/core/utils/context_processors.py, coldfront/static/common/css/common.css, coldfront/templates/common/navbar_admin.html, coldfront/templates/common/navbar_nonadmin_staff.html
**Changes**
- Display bubble alerts containing the number of pending requests for the relevant request types on navbar and dropdowns for Admin (superuser) and Staff users.
- Displays sum of counts next to "Requests" and "All Requests" items, as well as next to the "Admin" or "Staff" menu item.
- Calculates request counts in `context_processors.py`
**Testing**
- To manually/visually test, log in as a superuser or staff user, ensure that a yellow badge with a number appears on "Staff" or "Admin" navbar item.
- If you click down to "Requests," all request types with 1 or more pending request should also have badges. Go to "All Requests" and you can ensure the numbers displayed in the dropdown match those on the "All Requests" (`/user/request-hub-admin`) page.
=> Issue 598: Display pending request count for each request type

coldfront/core/project/forms_/new_project_forms/request_forms.py
**Changes**
- Updated the label for a computing allowance in the first step of the new project request form from e.g.,
- "Faculty Computing Allowance (Computing Allowance)" to "Faculty Computing Allowance"
- "Recharge Allocation (Computing Allowance)" to "Recharge Allocation"
- Ensure that the redundant suffix no longer appears.
=> Simplify labels for computing allowances in new project request form step

bootstrap/development/docker/images/os.Dockerfile
Some functionality may only be tested at certain times of the year. For example, the command `start_allocation_period`, which runs processing to allocate service units to projects under which renewals were requested, may only be run once the provided period has started.
`libfaketime` enables the current date and time of the machine to be mocked to test functionality like this beforehand. It had been used before, but had not been incorporated into the Docker development environment.
- Installed `libfaketime` in the `os` Docker image, which is inherited by other images.
- Updated the …
=> Install libfaketime in base Docker image

coldfront/core/statistics/templates/job_list.html, coldfront/core/statistics/tests/test_job_views.py, coldfront/core/statistics/utils_/job_accessibility_manager.py, coldfront/core/statistics/utils_/job_query_filtering.py, coldfront/core/statistics/views.py
Fixes #649
- Enabled all users to view and use the "Export Job List to CSV" on the Job List view.
- Refactored view logic with respect to session storage and user-job access into dedicated utility classes.
- Superusers and those with the `statistics.view_job` permission (e.g., staff users) may view and export all jobs.
- Project PIs and managers may view and export:
- Their own jobs across any project, and
- Jobs submitted by any user under projects they manage.
- Other users may view and export their own jobs.
- Limited the maximum number of jobs that may be exported to 100,000.
- An error appears if an …
=> Allow all users to export jobs to CSV

coldfront/core/project/tests/test_views/test_new_project_views/test_savio_project_request_wizard.py, coldfront/core/project/views_/new_project_views/request_views.py, coldfront/core/user/urls.py, coldfront/core/user/views.py, coldfront/core/utils/management/commands/export_data.py
This PR accounts for the fact that the `coldfront.plugins.departments` plugin may not be included in `INSTALLED_APPS` and thus will not be importable when is it disabled.
- Moved any module-level imports of the plugin into functions, after a check has been done to ensure that the plugin is enabled.
- Added a necessary check in `user.urls` for whether the app is installed before importing `coldfront.plugins.departments.views`, since feature flags are not usable at module load time.
- Refactored `SavioProjectRequestWizard` to dynamically insert the department form at instantiation when the flag is enabled, …
=> Allow for coldfront.plugins.departments being disabled

coldfront/core/project/views_/removal_views.py
Fix requester field lookup on project removal requests. The issue was the code thought the requester was a ProjectUser but it was actually just a user.
Fixes #(issue number) 
Asserted that looking up a user by requester name worked without erroring.
Strikethrough things that don’t make sense for your PR.
=> fixed requester lookup on project removal requests

coldfront/core/project/tests/test_utils/test_new_project_user_utils/test_runners.py, coldfront/core/project/utils_/new_project_user_utils.py
When a user is added to (or joins) a project on the Vector cluster, our policy is to automatically grant them access to a specific project on the Savio cluster (namely, the one specified in the SAVIO_PROJECT_FOR_VECTOR_USERS setting). This PR fixes that issue.
Fixes #656
Added a test case and ran it, ensuring it passed. Also manually tested by joining vector projects.
Strikethrough things that don’t make sense for your PR.
=> Issue 656: Bug when adding vector users 

coldfront/config/settings.py, requirements.txt
- Included `crispy-bootstrap4` as a dependency, which provides template packs for Bootstrap 4, which were removed by an update to the `django-crispy-forms` dependency.
**** Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any …
=> [OS/Python Upgrade] Retain support for Bootstrap 4 after django-crispy-forms upgrade

coldfront/core/allocation/management/commands/parse_academic_calendar.py, requirements.txt
Add a parse_academic_calendar command.
Note: Currently only supports the openai api. Adding more apis would require more libraries added in "requirements.txt"
Fixes #673 
- New feature (non-breaking change which adds functionality)
Outputs the following for "2025-26":
{
"academic_year": "2025-26",
"semesters": [
{
"name": "Fall",
"start_date": "2025-08-20",
"end_date": "2025-12-19"
},
{
"name": "Spring",
"start_date": "2026-01-13",
"end_date": "2026-05-15"
},
{
"name": "Summer",
"start_date": "2026-05-26",
"end_date": "2026-08-14"
}
]
Strikethrough things that don’t make sense for your PR.
=> Issue 673: Add parse_academic_calendar command

coldfront/core/portal/templates/portal/nonauthorized_home.html, coldfront/core/socialaccount/adapter.py, coldfront/core/socialaccount/tests/mocking.py, coldfront/core/socialaccount/tests/test_cilogon_account_adapter.py, coldfront/core/user/templates/user/sso_login_brc.html, coldfront/core/user/templates/user/sso_login_lrc.html, coldfront/templates/common/navbar_login.html, coldfront/templates/common/nonauthorized_navbar.html
- Corrected an import of a `django-allauth` utility method `valid_email_or_none`, given that it was moved.
- Updated login buttons to make POST, not GET requests, per `django-allauth`'s suggestion. After an update to the package, an additional redirect screen with a "Continue" button was introduced when a GET request was made, which would have changed and lengthened the process for users.
- Updated navbar …
=> [OS/Python Upgrade] Auth bug fixes: update util import; use POST, not GET, to login/logout

.github/workflows/django_testing_ci_python_3_13.yml, bootstrap/ansible/settings_template.tmpl, coldfront/config/local_settings.py.sample, coldfront/config/test_settings.py.sample, coldfront/core/allocation/tests/test_commands/test_start_allocation_period.py, coldfront/core/socialaccount/adapter.py, coldfront/core/utils/tests/test_base.py
- Fixed a variety of warnings.
- Notably, added 'retry' and 'timeout' keys to the `Q_CLUSTER` setting to suppress a warning about retry not being larger than timeout. The timeout is now set to a conservative 24 hours, with retries being attempted an additional 24 hours later. (In practice, the longest task at the moment takes less than 10 minutes.)
- Bug …
=> [OS/Python Upgrade] Fix Python warnings; set Q_CLUSTER settings

bootstrap/ansible-almalinux8/playbook.yml
- Updated the new Ansible playbook to deny 80/tcp traffic when Cloudflare is enabled, per Berkeley Lab [policy](https://commons.lbl.gov/spaces/cpp/pages/81660736/Open+Web+Server+Requirements#OpenWebServerRequirements-Requirement4%3ASSLconfiguredon443%2Ftcp).
**** Please describe the tests that you ran …
=> [OS/Python Upgrade] Deny 80/tcp traffic when Cloudflare is enabled in new Ansible playbook

coldfront/core/allocation/management/commands/send_allowance_renewal_available_emails.py, coldfront/core/project/utils_/renewal_utils.py, coldfront/templates/email/project_renewal/project_renewal_available.html, coldfront/templates/email/project_renewal/project_renewal_available.txt
- Added a management command `send_allowance_renewal_available_emails` that notifies active FCA (MyBRC) / PCA (MyLRC) project PIs and managers that renewal for the next allowance year is available.
- Emails are only sent if a readiness audit of the period passes (see the `audit_allocation_period` command).
- A `--dry_run` flag may be provided to test.
- Added supporting utilities.
It is the administrator's responsibility not to run the command repeatedly.
- New feature (non-breaking change which adds functionality)
**** Please describe the tests that …
=> Add command to notify project owners that FCA/PCA renewal for next year is available
